const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('piu', {
  getCurrentWeek: () => ipcRenderer.invoke('piu:getCurrentWeek'),
  isOrdersOpen: () => ipcRenderer.invoke('piu:isOrdersOpen'),
  getDashboard: () => ipcRenderer.invoke('piu:getDashboard'),
  addProduction: (dishId, quantity) => ipcRenderer.invoke('piu:addProduction', { dishId, quantity }),
  undoProduction: (dishId) => ipcRenderer.invoke('piu:undoProduction', { dishId }),
  getOrders: () => ipcRenderer.invoke('piu:getOrders'),
  createOrder: (data) => ipcRenderer.invoke('piu:createOrder', data),
  updateOrder: (data) => ipcRenderer.invoke('piu:updateOrder', data),
  deleteOrder: (id) => ipcRenderer.invoke('piu:deleteOrder', { id }),
  getOrderWithDetails: (id) => ipcRenderer.invoke('piu:getOrderWithDetails', { id }),
  getOrdersByWeekId: (weekId) => ipcRenderer.invoke('piu:getOrdersByWeekId', { weekId }),
  getDishes: () => ipcRenderer.invoke('piu:getDishes'),
  createDish: (data) => ipcRenderer.invoke('piu:createDish', data),
  updateDish: (data) => ipcRenderer.invoke('piu:updateDish', data),
  deleteDish: (id) => ipcRenderer.invoke('piu:deleteDish', { id }),
  getClients: () => ipcRenderer.invoke('piu:getClients'),
  createClient: (data) => ipcRenderer.invoke('piu:createClient', data),
  updateClient: (data) => ipcRenderer.invoke('piu:updateClient', data),
  deleteClient: (id) => ipcRenderer.invoke('piu:deleteClient', { id }),
  getAnalytics: () => ipcRenderer.invoke('piu:getAnalytics'),
  getIngredientsList: () => ipcRenderer.invoke('piu:getIngredientsList'),
  getWeekComparison: () => ipcRenderer.invoke('piu:getWeekComparison'),
  getPreviousWeeks: () => ipcRenderer.invoke('piu:getPreviousWeeks'),
  completeDishProduction: (dishId) => ipcRenderer.invoke('piu:completeDishProduction', { dishId }),
  markOrderAssembled: (id) => ipcRenderer.invoke('piu:markOrderAssembled', { id }),
  unmarkOrderAssembled: (id) => ipcRenderer.invoke('piu:unmarkOrderAssembled', { id }),
  clientHasOrderThisWeek: (clientId) => ipcRenderer.invoke('piu:clientHasOrderThisWeek', { clientId }),
  getMonthlyTrend: () => ipcRenderer.invoke('piu:getMonthlyTrend'),
  getYearlyTrend: () => ipcRenderer.invoke('piu:getYearlyTrend'),
  getMonthComparison: () => ipcRenderer.invoke('piu:getMonthComparison'),
  getYearComparison: () => ipcRenderer.invoke('piu:getYearComparison')
})
